# Generated by Django 3.2 on 2023-08-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all',
        ),
    ]
