# Generated by Django 3.2 on 2023-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('AutoField', models.AutoField(primary_key=True, serialize=False)),
                ('BigIntegerField', models.BigIntegerField()),
                ('BinaryField', models.BinaryField()),
                ('BooleanField', models.BooleanField()),
                ('CharField', models.CharField(max_length=255)),
                ('DateField', models.DateField()),
                ('DateTimeField', models.DateTimeField()),
                ('DecimalField', models.DecimalField(decimal_places=2, max_digits=4)),
                ('DurationField', models.DurationField()),
                ('EmailField', models.EmailField(max_length=254)),
                ('FileField', models.FileField(upload_to='')),
                ('FilePathField', models.FilePathField()),
                ('FloatField', models.FloatField()),
                ('GenericIPAddressField', models.GenericIPAddressField()),
                ('ImageField', models.ImageField(upload_to='')),
                ('IntegerField', models.IntegerField()),
                ('JSONField', models.JSONField()),
                ('PositiveBigIntegerField', models.PositiveBigIntegerField()),
                ('PositiveIntegerField', models.PositiveIntegerField()),
                ('PositiveSmallIntegerField', models.PositiveSmallIntegerField()),
                ('SlugField', models.SlugField()),
                ('SmallIntegerField', models.SmallIntegerField()),
                ('TextField', models.TextField()),
                ('TimeField', models.TimeField()),
                ('URLField', models.URLField()),
                ('UUIDField', models.UUIDField()),
            ],
        ),
    ]
