# Generated by Django 3.2 on 2023-08-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='BigIntegerField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='DecimalField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='DurationField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='FilePathField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='FloatField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='GenericIPAddressField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='JSONField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='PositiveBigIntegerField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='PositiveIntegerField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='PositiveSmallIntegerField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='SmallIntegerField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='URLField',
        ),
        migrations.RemoveField(
            model_name='all',
            name='UUIDField',
        ),
    ]
