# Generated by Django 3.2 on 2023-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_delete_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
