# Generated by Django 3.2 on 2023-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
