# Generated by Django 3.2 on 2023-08-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
